первое решение - pull
Skzo82/sprint_6-solution pull request #1
Opened 2024-12-04 12:53 UTC by Skzo82

2024-12-04 12:57 UTC, Skzo82 commented
Я хотел посмотреть, как это работает, извини

2024-12-05 12:38 UTC, Fleaman777 requested changes
хорошо, возвращаю на доработку

2024-12-05 16:18 UTC, Skzo82 commented
> хорошо, возвращаю на доработку

Я имел в виду, что я написал один и тот же код дважды, удалив комментарии, потому что хотел понять, как отправить Pull. Мне пора заканчивать, думаю, код.

2024-12-06 13:20 UTC, Fleaman777 requested changes
все же есть что поправить. 
приложение должно состояить из старого функционала (управление задачми) и из нового - обновленного менеджера истории, 
а тут получается, репозиторий связанный только с менеджером истории. 
код написан хорошо, и должен работать корректно, но это только часть задания, которая должна быть вместе с другим(старым) кодом,

Так же в задании необходимо добавить новые тесты, которые описаны в ТЗ

поэтому жду написанно здесь решения вместе со старым функционалом

2024-12-06 17:47 UTC, Skzo82 commented
> все же есть что поправить. приложение должно состояить из старого функционала (управление задачми) и из нового - обновленного менеджера истории, а тут получается, репозиторий связанный только с менеджером истории. код написан хорошо, и должен работать корректно, но это только часть задания, которая должна быть вместе с другим(старым) кодом,
> 
> Так же в задании необходимо добавить новые тесты, которые описаны в ТЗ
> 
> поэтому жду написанно здесь решения вместе со старым функционалом

Я не понимаю, стоит ли мне взять код спринта 5 и доработать его, добавив новые функционалом?

2024-12-07 21:14 UTC, Fleaman777 requested changes
отлично, этой части приложения и не хватало. 
Есть что поправить, но по крайней мере понятно что)

2024-12-07 21:14 UTC, Fleaman777 commented on TaskManager/src/taskmanager/tasks/Node.java
> +}
по сути, Node класс не имеет особого смысла без логики, которая реализована в InMemoryHistoryManager, поэтому его можно было бы сделать внутренним классом в InMemoryHistoryManager.

2024-12-07 21:14 UTC, Fleaman777 commented on TaskManager/src/taskmanager/managers/InMemoryTaskManager.java
> +    }
использовании методов removAll.... так же может повлиять на состояние менеджера истории

2024-12-07 21:14 UTC, Fleaman777 commented on TaskManager/src/taskmanager/managers/InMemoryHistoryManager.java
> +    private static class DoublyLinkedList {
в целом, эту логику можно было бы расположить напрямую в InMemoryHistoryManager классе

2024-12-07 21:14 UTC, Fleaman777 commented on TaskManager/src/taskmanager/Test/InMemoryTaskManagerTest.java
> +}
неплохие тесты, покрывают часть функционала, но так же еще необходимо добавить те, которые упомянуты в ТЗ

2024-12-07 21:14 UTC, Fleaman777 commented on TaskManager/src/taskmanager/Test/InMemoryTaskManagerTest.java
> +public class InMemoryTaskManagerTest {
помимо этого тестового класса, должно быть еще несколько, которые проверяют работу менеджера задач, написанные в пред спринте

2024-12-11 20:53 UTC, Fleaman777 approved these changes
выглядит отлично, молодец, правильные исправления! 
Хорошо постарался, можно идти дальше

2025-01-15 19:59 UTC, merged